version: "3.7"
services:
  api:
    build: .

  seed_marquez:
    build: .

  pghero:
    image: ankane/pghero
    container_name: pghero
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432
